### ISSUE TITLE
Latest version on Pub is 0.5.0.

### ISSUE THREAD

**Issue by FCMHUB** [CallumIddon/bloc_generator#3]
Thanks for this awesome package.

Latest version on Pub is 0.4.0 instead of 0.5.0.
Is there any reason for that?

**Comment by CallumIddon** [comment]
From 0.5.0 onwards I wanted a CI server to automatically publish the packages but I was having problems getting it to work. I have since fixed the issue and rolled some more changes into the 0.5.0 release.
